### ISSUE TITLE
Testing WebApp: "open vragen en antwoorden weergeven"

### ISSUE THREAD

**Issue by kitesaint1309** [Rival-Thompson/CloudApplications-TeachMe#54]
Testing van een correcte weergave en werking van de pagina "open vragen en antwoorden"
- [x] Weergave vraag
- [ ] Weergave antwoorden
- [ ] Visualisatie

**Comment by Rival-Thompson** [comment]
Werkt goed enkel nog het dynamisch updaten moet gebeuren!
@kitesaint1309
