### ISSUE TITLE
Testing WebApp: "multiple choice vragen en antwoorden weergeven"

### ISSUE THREAD

**Issue by kitesaint1309** [Rival-Thompson/CloudApplications-TeachMe#57]
Testing van een correcte weergave en werking van de pagina "multiple choice vragen en antwoorden"
- [ ] Weergave vraag en opties
- [ ] Weergave antwoorden
- [ ] Visualisatie

**Comment by Rival-Thompson** [comment]
Werkt goed enkel nog het dynamisch updaten moet gebeuren!
@kitesaint1309
